#%RAML 1.0 DataType
type: object
displayName: customer-address
properties:
  id?: string
  address?: string
  address-line-2?: string
  address-line-3?: string
  address-line-4?: string
  city?: string
  state?: string
  postal-code?: string
  country?: string