#%RAML 1.0 DataType
type: object
displayName: customerAddress
properties:
  id?: string
  address?: string
  addressLine2?: string
  addressLine3?: string
  addressLine4?: string
  city?: string
  state?: string
  postalCode?: string
  country?: string