#%RAML 1.0 DataType
type: object
displayName: charging-plan
properties:
  contract-start-date?: date-only
  contract-end-date?: date-only
  unit-of-sale?: string
  units-of-sale-amount?: number
  fee-type?: string
  product-version-list?: string
  usage-reporting-system?: boolean