#%RAML 1.0 DataType
type: object
displayName: customer
properties:
  legacyCustomerCode?: string
  accountNumber?: string
  customerContact?:
    displayName: customer contact details
    type: !include contact.raml
  organisationName?: string
  customerAddress?:
    displayName: customer address details
    type: !include address.raml
