#%RAML 1.0 DataType
type: object
displayName: orderLine
properties:
  orderLineId?: string
  order?:
    displayName: order details
    type: !include order.raml
  product?: 
    displayName: customer details
    type: !include product.raml
  chargingType?: string
  shippingAddress?: string
  chargingPlan?: 
    displayName: charging plan details
    type: !include chargingplan.raml
  
  
