#%RAML 1.0 DataType
type: object
displayName: customerContact
properties:
  firstName?: string
  lastName?: string
  title?: string
  email?: string
  telephone?: string
  supportTeam?: string
  role?: string