#%RAML 1.0 NamedExample
    id: ""
    address: "xyz street"
    addressLine2: "add2"
    addressLine3: "add3"
    addressLine4: ""
    city: "London"
    state: "London"
    postalCode: "LU1"
    country: "UK"