#%RAML 1.0 NamedExample
    id: ""
    address: "32A Stuart St"
    addressLine2: "Luton"
    addressLine3: ""
    addressLine4: ""
    city: "Luton"
    state: ""
    postalCode: "LU1"
    country: "UK"