#%RAML 1.0 NamedExample
    id: ""
    address: "xyz street"
    address-line-2: "add2"
    address-line-3: "add3"
    address-line-4: ""
    city: "London"
    state: "London"
    postal-code: "LU1"
    country: "UK"