#%RAML 1.0 NamedExample
    contractStartDate: 2019-10-03
    contractEndDate: 2020-10-02
    unitOfSale: "C"
    unitsOfSaleAmount: 0
    feeType: "A"
    productVersionList: ""
    usageReportingSystem: false