#%RAML 1.0 NamedExample
    contract-start-date: 2019-10-03
    contract-end-date: 2020-10-02
    unit-of-sale: "C"
    units-of-sale-amount: 0
    fee-type: "A"
    product-version-list: ""
    usage-reporting-system: false