#%RAML 1.0 NamedExample
    legacy-customer-code: "we-12-wd-34"
    account-number: "1234567891"
    contact: !include contact.raml
    organisation-name: "Org1"
    customer-address: !include address.raml