#%RAML 1.0 NamedExample
    legacyCustomerCode: "we-12-wd-34"
    accountNumber: "1234567891"
    type: "Marine"
    customerContact: !include contact.raml
    companyName: "AVEVA"
    customerAddress: !include address.raml
    telephone: "0446518947345"