#%RAML 1.0 NamedExample
    legacyCustomerCode: "we-12-wd-34"
    accountNumber: "1234567891"
    contact: !include contact.raml
    organisationName: "Org1"
    customerAddress: !include address.raml