#%RAML 1.0 NamedExample
    order-line-id: "2875"
    order: !include order.raml
    product: !include product.raml
    charging-type: "GBP"
    shipping-address: "en-gb"
    charging-plan: !include charging-plan.raml