#%RAML 1.0 NamedExample
    item-name: "12"
    versioning: "1.0"
    legacy-product-code: "we-34-dd"
    commercial-name: "xyz"
    item-class: "class1"
    status: "Active"
    comments: "Product Details"