#%RAML 1.0 NamedExample
    productCode: "12"
    versioning: "1.0"
    legacyProductCode: "we-34-dd"
    commercialName: "xyz"
    productClass: "class1"
    status: "Active"
    comments: "Product Details"