#%RAML 1.0 Trait

queryParameters:
  offset?:
    description: Skip over a number of elements by specifying an offset value for the query
    type: integer
    example: 20
    default: 0
  limit?:
    description: Limit the number of elements on the response
    type: integer
    example: 80
    default: 10
  page?:
    type: integer
    default: 1
    minimum: 1
    description: The `page` parameter specifies the page of results to return.
  Is-First-Page?:
    type: boolean
    default: true
    description: The `first-page` parameter specifies that the page is first page or not.
  Is-Last-Page?:
    type: boolean
    default: false
    description: The `page` parameter specifies the page that the page is last page or not.