#%RAML 1.0 Library
usage:

traits:
  orderable: !include orderable.raml
  pageable: !include pageable.raml
  secured: !include secured.raml
  traceable: !include traceable.raml
  overridable: !include overridable.raml
  actionable: !include actionable.raml
