#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/65a1549f-ef35-4c92-a70d-8ba0be6f4d02/ # 
title: x-orderlines-api
version: v1

uses:
  dataTypesLib: exchange_modules/600fe2e7-d5ea-4266-abb3-7fb67efb9c53/datatypeslibrary/1.0.0/datatypeslibrary.raml
  resourceTypesLib: exchange_modules/600fe2e7-d5ea-4266-abb3-7fb67efb9c53/resourcetypeslibrary/1.0.1/resourcetypeslibrary.raml
  traitsLib: exchange_modules/600fe2e7-d5ea-4266-abb3-7fb67efb9c53/traitslibrary/1.0.1/traitslibrary.raml
  
/erpOrderLines:
  description: |
        Resource to update order line fulfilment status coming from Orcle-ERP System based on order id and order line id.
  /{erpOrderId}:
    description: |
        ERP Order identifier 
    /{erpOrderLineId}:  
      description: |
        ERP Order line identifier; with erpOrderId and X-ErpAccountNumber, uniquely identifies an ERP Order line
      type:
        resourceTypesLib.member:
      is: [traitsLib.traceable: {required: true}, traitsLib.secured: {required: true}]
      put:
        description: |
          Upsert orderline to target system. e.g CALM2
        securedBy: [traitsLib.oauth_2_0]
        headers:
          ERP-Account-Number:
            type: string
            description: |
              Legacy Navision or other system customer code, aka Navision account number or Reference for existing customer or new ERP customer code. Specifies the customer for ALAs. Must match the Connect Account for CLAs             
        body:
          application/json:
            example: !include examples/update-order-lines.raml
            properties:
              orderLine: dataTypesLib.orderLine
              customer: dataTypesLib.customer
              licenseFactory: dataTypesLib.licenseFactory
        responses:
          200:
            body:
              application/json:
                example: |
                      { "responseCode" : 0,  "responseText" : "success"}
/erpLicenseFulfillmentStatus:
  description: |
        Resource to update license fulfillment status in ERP system where the request coming from source system like CALM2.
  /{erpOrderId}:
    description: |
        ERP Order identifier 
    /{erpOrderLineId}:  
      description: |
        ERP Order line identifier; with erpOrderId and X-ErpAccountNumber, uniquely identifies an ERP Order line
      type:
        resourceTypesLib.member:
      is: [traitsLib.traceable: {required: true}, traitsLib.secured: {required: true}]
      put:
        description: |
          Update license fulfilment status to ERP system
        headers:
          ERP-Account-Number:
            type: string
            description: |
              Legacy Navision or other system customer code, aka Navision account number or Reference for existing customer or new ERP customer code. Specifies the customer for ALAs. Must match the Connect Account for CLAs             
        body:
          application/json:
            example: !include examples/license-fulfillment-status.raml
            properties:
              statusId: dataTypesLib.statusId
              statusInfo: dataTypesLib.statusInfo
        responses:
          200:
            body:
              application/json:
                example: |
                      { "responseCode" : 0,  "responseText" : "success"}                
